### ISSUE TITLE
Problem with components that cause reflow during rendering

### ISSUE THREAD

**Issue by satazor** [react-component/animate#10]
The `Animation` component adds the `<transition>-enter` class when the transition is about to be done. Though, for components that perform synchronous DOM read operations during mount, the component will be drawn immediately and only later the `<transition>-enter` class will be added. This obviously causes issues when doing page transitions (e.g.: animating opacity).

I've had to do a workaround to circumvent the issue:

```js
class Application extends Component {
    componentWillUpdate(prevProps) {
        prevProps.location.pathname !== this.props.location.pathname && this._toggleAnimationClass(true);
    }

    render() {
        return (
            <div id="application">
                <div id="page">
                    <Animation component="div" transitionName="page-transition"
                        ref={ (ref) => { this._animationComponent = ref; } }
                        onEnter={ () => this._toggleAnimationClass(false) }>
                      { React.cloneElement(this.props.children, { key: this.props.location.pathname }) }
                    </Animation>
                </div>
            </div>
        );
    }

    _toggleAnimationClass(active) {
        ReactDOM.findDOMNode(this._animationComponent).classList.toggle('page-transition', active);
    }
}

export default Application;
```

Now, I set the initial CSS styles I want using `.page-transition > .page:first-of-type` instead of `.page-transition-enter`.

Let me know if you want a reproducible project to debug.

**Comment by yiminghe** [comment]
yeah, a reproducible demo is welcome

**Comment by satazor** [comment]
@yiminghe I'm no longer using this component.. feel free to close the issue if you want.
