### ISSUE TITLE
Incompatibility with css-modules

### ISSUE THREAD

**Issue by alexbardas** [react-component/animate#14]
Hi,

rc-animate seems to be incompatible with css-modules right now. More context about this issue can be found [here](https://github.com/css-modules/css-modules/issues/84#issuecomment-226731145). If transitionName is an object, appearActive, enterActive and leaveActive properties are not used.

There's also an [issue in css-animate](https://github.com/yiminghe/css-animation/blob/bcd6ce3b0d5a49a466e2858e9dadfd29c7f16dcd/src/index.js#L51) because '-active' is hardcoded for any animation.

Css modules seems to have quite a big adoption right now, so a backwards compatible change would make sense in my opinion.

**Comment by yiminghe** [comment]
```
transitionName={{
    enter: style.enter,
    enterActive: style.enterActive,
    leave: style.leave,
    leaveActive: style.leaveActive,
  }}
```
