### ISSUE TITLE
JS Animation

### ISSUE THREAD

**Issue by FredHasselot** [react-component/animate#17]
Hi,

I'm trying to animate an image on appear, enter and leave with JS.
i'm doing something like that: 

```
<Animate
          component=""
          transitionAppear={false}
          transitionEnter={false}
          transitionLeave={false}
          onEnd={this.animateEnded.bind(this)}
          animation={this.state.animationObject}>
          {
            this.state.imageStatus &&
            <img
              key={new Date()}
              ref="image"
              src={this.state.currentImgSource}>
            </img>
           }
</Animate>
```

The appear event work correctly and is triggered but the others are not.
I only change imageStatus state to true or false if img is loaded or not.

When i set imgStatus state to false the img disappear without the leave animation and the appear animation is triggered again...
it should not, right ? :)

(i added a key on the img tag, with a date, i don't know if i have to do this)

I don't figure out what i'm doing wrong...
Thanks

**Comment by hqwlkj** [comment]
请问  Animate 的onEnd事件 怎么触发？
