### ISSUE TITLE
exclusive not making it exclusive

### ISSUE THREAD

**Issue by juliocesar** [react-component/animate#2]
Hey sir. Thanks a bunch for this library!

Not sure whether that's intended or not, but setting `exclusive={true}` isn't ensuring that an element currently in the DOM is allowed to *finish* its leave transition before the next one entering. 

Is that a bug, or am I misinterpreting how it works?

Thanks!

**Comment by yiminghe** [comment]
try install 1.0.4.

If not works, can you point me a demo? exclusive will make current animation stop immediately

https://github.com/react-component/animate/blob/f3d61107c6ed73ac514febb599d91b811b799780/src/Animate.js#L87

**Comment by juliocesar** [comment]
Hey!

Yeah, I think I misunderstood it. I thought `exclusive` made the `enter` animation wait until a `leave` animation is finished.

I'll see if I can add that myself.

**Comment by xujihui1985** [comment]
@juliocesar  see example for exclusive, http://react-component.github.io/animate/examples/exclusive.html, this has been fixed in 1.0.5

**Comment by juliocesar** [comment]
@xujihui1985 Hey! Thank you. Just checked, and I don't think it's a bug in `exclusive` per se.

I thought exclusive meant that before the next component enters, that it would wait for a current one to leave, and *only then* be put in the DOM and animate, but that's not how it works at all.

In my case at least, `exclusive` doesn't seem to make any difference (toggling it on or off yields the same result).

**Comment by xujihui1985** [comment]
@juliocesar  exclusive here means, stop the current one before next compnent enters, and that should make difference when toggling it or or off, try to clone the latest code and toggle the property in examples/exclusive.js to see the difference :)

**Comment by yiminghe** [comment]
non exclusive: http://react-component.github.io/animate/examples/simple.html

exclusive: http://react-component.github.io/animate/examples/simple-exclusive.html

**Comment by juliocesar** [comment]
@xujihui1985 @yiminghe Many thanks!

Yeah, I misunderstood it. I was looking for a way to queue the enter/leave process. Will ping back here if I come up with something.

This is what I'm cooking with it -> https://gist.github.com/juliocesar/ae67cc40593d71e2f5e4
