### ISSUE TITLE
Please bump version in npm repo

### ISSUE THREAD

**Issue by sujameslin** [react-component/animate#21]
Github repo version is 2.3.4, but npm repo's 2.3.3.
Can you please push to npm repo?

**Comment by paranoidjk** [comment]
cc @yesmeck

**Comment by yesmeck** [comment]
I don't have permission. @yiminghe

**Comment by yesmeck** [comment]
2.3.4 has released.

**Comment by afc163** [comment]
https://github.com/react-component/animate/blob/f1c48464a8a4149bf647f2ffe6bcdee9f4091b67/src/Animate.js#L265

这里还有个 isMounted
