### ISSUE TITLE
设置 component 属性的问题

### ISSUE THREAD

**Issue by likun7981** [react-component/animate#24]
When  the `component` property is set to`""`, it will only render the first child node. it will cause a result  that the leave animation is executing,  because only render the first child , so `this.refs` is no reference to the child node behind first.  so  the `leave animation` is  not normal , It is advisable to give a warning when there is a `leave` animation

当设置 `component` 属性 为 `""`的时候， 就只会渲染第一个孩子节点，导致 `this.refs` 没有引用到后面的孩子节点，所以除第一个外的后面的孩子节点的离开动画不会正常触发， 建议在设置离开动画的时候，如果设置`component=""`时 ， 给一个警告信息

**Comment by jljsj33** [comment]
set to '' if you do not wrap for only one child

**Comment by benjycui** [comment]
Usage question.
