### ISSUE TITLE
Lastest publish as minor breaks dependents due to api change.

### ISSUE THREAD

**Issue by Nicktho** [react-component/animate#27]
This commit https://github.com/react-component/animate/commit/fdec45af3fc62de7a03c2554ff0bfc2fff97e318

Has broken our code that requires in this module, as it has changed the export to require `.default()`. Could a patch be released to revert this change and a major bump be released with this change so our services dependent on `2.x.x` don't break?

**Comment by paranoidjk** [comment]
I don't konw what's your use case, it should be no problem.

see https://unpkg.com/rc-animate@2.4.0

```js
exports['default'] = Animate;
module.exports = exports['default'];
```

**Comment by Nicktho** [comment]
Closing this, I was seeing the issue when parsing a file that was importing animate with acorn v3. Acorn v5 handled it correctly. Thanks! :)

**Comment by anyexinglu** [comment]
> I don't konw what's your use case, it should be no problem.
> 
> see https://unpkg.com/rc-animate@2.4.0
> 
> ```js
> exports['default'] = Animate;
> module.exports = exports['default'];
> ```

```
import Animate from 'rc-animate'; => Animate is undefined
import * as Animate from 'rc-animate'; => Animate is right
```
