### ISSUE TITLE
React 0.14 Compability

### ISSUE THREAD

**Issue by natorojr** [react-component/animate#3]
Hello,

The latest release of this project is not React 0.14 compatible and, hence, is the underlying cause of console warning/error messages for its dependents.

> Warning: React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.

https://github.com/react-component/animate/blob/master/src/AnimateChild.js#L17

**Comment by natorojr** [comment]
Create PR #4

**Comment by yiminghe** [comment]
thanks
