### ISSUE TITLE
css-animation 1.4.0 breaks transpiling

### ISSUE THREAD

**Issue by wallaroo** [react-component/animate#30]
hi, css-animation 1.4.0 added the module field in its package.json (https://github.com/yiminghe/css-animation/commit/2005b5adc1f49b6c7683b7e06c010aee8b35bdaa) and now when rc-animate is a dependency of a create-react-app project the build fails with 

> css-animation' does not contain an export named 'isCssAnimationSupported

i've also created an issue on css-animation https://github.com/yiminghe/css-animation/issues/13

**Comment by VanDavv** [comment]
also referenced here https://github.com/yiminghe/css-animation/issues/14

**Comment by rafauke** [comment]
Confirmed. Obviously, easy fix is just:

```
9 | import cssAnimate from 'css-animation';
...
76 | if ((cssAnimate.isCssAnimationSupported || !props.animation[animationType]) && transitionName && props[transitionMap[animationType]]) { ... }
```
doesn't look great though ;)
