### ISSUE TITLE
Animate.js 的 defaultKey 的生成方式导致 jest mock 的 Date.now 无法起作用

### ISSUE THREAD

**Issue by someok** [react-component/animate#32]
这个问题是在使用 `jest` 的 `toMatchSnapshot` 时候发现的，debug 了一下发现是下面语句无论如何都会在 mock 的`Date.now = jest.fn(() => 1507453184412)` 之前执行，所以建议这个语句是不是应该放到 `Animate.js` class 的内部更好？

```
const defaultKey = `rc_animate_${Date.now()}`;

```

**Comment by benjycui** [comment]
[setupFiles](https://facebook.github.io/jest/docs/en/configuration.html#setupfiles-array).

**Comment by someok** [comment]
其实不能用 setupFiles 来处理，毕竟这个 Date 的 mock 只是在某个测试中使用。

应该使用 `enzyme-to-json` 的 `noKey` 属性

```
import toJson from 'enzyme-to-json';

expect(toJson(wrapper, {noKey: true})).toMatchSnapshot();
```
