### ISSUE TITLE
Why not return the children directly

### ISSUE THREAD

**Issue by likun7981** [react-component/animate#33]

**Comment by yesmeck** [comment]
Because React 15 don't allow return a array from component, consider following use case:

```javascript
<Animate>
  <li>1</li>
  <li>2</li>
</Animate>
```

**Comment by yesmeck** [comment]
I think we should use `React.Children.only` instead of `children[0]`.

**Comment by likun7981** [comment]
That is because React16 support so I asked this question,  I think you can release a version for react16.

**Comment by yesmeck** [comment]
https://github.com/react-component/animate/issues/34
