### ISSUE TITLE
[Discuss] Add CSSTransition component

### ISSUE THREAD

**Issue by zombieJ** [react-component/animate#40]
Since current Animate component mixed with js operation, it's not easy for virtualized component animation (which need calculate style after `didUpdate`). Here is the plan for adding a new sub component called `CSSTransition` using render props.

Draft:
```jsx
// Return customize style
onAppearStart = (ele) => ({ height: 0 });
```

```jsx
<CSSTransition visible={show} transitionName="transition" onAppearStart={onAppearStart}>
  {({ style, className }) => (
    <div className={className} style={style} />
  )}
</CSSTransition>
```

@afc163 @yesmeck

**Comment by yesmeck** [comment]
就是这个吗 https://github.com/reactjs/react-transition-group

**Comment by zombieJ** [comment]
> 就是这个吗 https://github.com/reactjs/react-transition-group

嗯，参考了它们。

**Comment by zombieJ** [comment]
把 style 在 `onXXX` 里返回让 style 也一并进入 React 管理就把 antd 里的 collapse 的 animate 也覆盖到了。要兼容 js 操作 dom 是绕了远路，应该 deprecated 掉。

**Comment by afc163** [comment]
可以的，更 React 一点。

**Comment by zombieJ** [comment]
Add pr on this: https://github.com/react-component/animate/pull/41
