### ISSUE TITLE
component 属性设置为 "" 时，元素消失动画失效

### ISSUE THREAD

**Issue by hellohejinyu** [react-component/animate#42]
[![Edit xj0xq1zpvz](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xj0xq1zpvz)

**Comment by zombieJ** [comment]
是有点问题，先用 `showProp` 来控制一下吧： https://codesandbox.io/s/52k4zr1xok

**Comment by zWingz** [comment]
同样遇到问题.
元素消失动画失效.
`onLeave`事件没有触发
