### ISSUE TITLE
componentWillReceiveProps will be deprecated

### ISSUE THREAD

**Issue by dsempel** [react-component/animate#44]
This method will be removed in the next major version of React (https://github.com/reactjs/rfcs/blob/master/text/0006-static-lifecycle-methods.md).

Here is some more info about replacing it: https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops

**Comment by ovaldi** [comment]
+1

**Comment by planless** [comment]
+100

**Comment by afc163** [comment]
fixed in https://github.com/react-component/animate/pull/82
