### ISSUE TITLE
Error on null/undefined children

### ISSUE THREAD

**Issue by gpoole** [react-component/animate#7]
`Animate` emits an exception if any of its children are null/undefined. Ideally I think it should use the same logic as `React.Children.toArray()` and simply [ignore invalid children](https://github.com/spicyj/react/blob/53d8bbddc7322f165b966f862043881ac31583a9/src/isomorphic/children/ReactChildren.js#L156)?

Not ignoring null children means patterns like this don't work:

```jsx
React.createClass({
  someOtherRenderFunction() {
    if (!this.state.spanIsNotVisible) {
      return;
    }

    return <span />;
  },
  
  someRenderFunction() {
    if (!this.state.divIsNotVisible) {
      return;
    }

    return <div />;
  },

  render() {
    return (
      <Animate>
        {this.someRenderFunction()}
        {this.someOtherRenderFunction()}
      </Animate>
    );
  }
});
```

This component is normally valid without `Animate`.

**Comment by yiminghe** [comment]
null/undefined has meaning.

```
const Inner3 = React.createClass({
  componentWillUnmount() {
    console.log('unmount', this.props.a);
  },
  render() {
    return <span>inner {this.props.a}</span>;
  },
});

ReactDOM.render(<div>
  <Inner3 a="1"/>
  <Inner3 a="2"/>
  <Inner3 a="3"/>
  </div>, document.getElementById('__react-content'));

ReactDOM.render(<div>
  <Inner3 a="1"/>
  {undefined}
  <Inner3 a="3"/>
</div>, document.getElementById('__react-content'));
```

you have to use array with key prop.

**Comment by gpoole** [comment]
Sorry, I think my example was misleading and I forgot to include `key` props in it. My point was that rc-animate throws an exception when undefined/null children are present (`Cannot read property 'key' of null`) and I think this is not correct. I think it just needs to skip null/undefined children in `findChildInChildrenByKey`, `findShownChildInChildrenByKey` and `findHiddenChildInChildrenByKey`?

A better example of a case that causes an exception:
```jsx
<Animate>
  {undefined}
  <div key='example'></div>
</Animate>
```

**Comment by yiminghe** [comment]
o, it will be easier to write, but we usually use a dynamic array, could you make a pr?
