### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by VladimirHumeniuk** [react-component/animate#79]
I'm using this package inside application with typescript, and I'm getting the next error:
```
Could not find a declaration file for module 'rc-animate'. 'node_modules/rc-animate/lib/Animate.js' implicitly has an 'any' type.
  Try `npm install @types/rc-animate` if it exists or add a new declaration (.d.ts) file containing `declare module 'rc-animate';`
```

**Comment by cahtyw** [comment]
`rc-animate` doens't have an `@types` yet, so you can't install with `npm i --save-dev @types/rc-animate`.

You can create a file like `./src/types.d.ts` and declare rc-animate module inside, like this:

`declare module 'rc-animate;`

**Don't forget to insert the follow line in the tsconfig.json**


```
{
  "compilerOptions": {
    ...
  },
  "files": ["src/types.d.ts"]
}
```
